# -*- coding: utf-8 -*-
"""ML-Med-Prac2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19u7PPyW6oStWjOSXptHrw8BQsxtRk6JF
"""

from google.colab import drive
drive.mount('/content/drive')

import os
import pandas as pd
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt

ROOT = "/content/drive/MyDrive/ML_MED/Prac2/Practical_2/"
TRAIN_IMG_DIR = os.path.join(ROOT, "training_set")
TRAIN_CSV = os.path.join(ROOT, "training_set_pixel_size_and_HC.csv")

df = pd.read_csv(TRAIN_CSV)
df["image_path"] = df["filename"].apply(lambda x: os.path.join(TRAIN_IMG_DIR, x))

df.head()

print("Number of training samples:", len(df))
print("HC statistics:")
df["head circumference (mm)"].describe()

plt.figure()
plt.hist(df["head circumference (mm)"], bins=30)
plt.xlabel("Head Circumference (HC)")
plt.ylabel("Count")
plt.title("HC distribution")
plt.show()

heights, widths, channels = [], [], []

for p in df["image_path"].sample(300, random_state=42):
    img = Image.open(p)
    arr = np.array(img)
    if arr.ndim == 2:
        h, w = arr.shape
        c = 1
    else:
        h, w, c = arr.shape
    heights.append(h)
    widths.append(w)
    channels.append(c)

size_df = pd.DataFrame({
    "height": heights,
    "width": widths,
    "channels": channels
})

size_df.describe()

stds = []

for p in df["image_path"].sample(300, random_state=1):
    img = Image.open(p)
    arr = np.array(img).astype(np.float32)
    stds.append(arr.std())

plt.figure()
plt.hist(stds, bins=30)
plt.xlabel("Pixel intensity standard deviation")
plt.ylabel("Count")
plt.title("Image contrast distribution")
plt.show()

samples = df.sample(9, random_state=0)

plt.figure(figsize=(9,9))
for i, (_, row) in enumerate(samples.iterrows(), 1):
    img = Image.open(row["image_path"])
    plt.subplot(3,3,i)
    plt.imshow(img, cmap="gray")
    plt.title(f"HC = {row['head circumference (mm)']:.1f}")
    plt.axis("off")
plt.tight_layout()
plt.show()

from sklearn.model_selection import train_test_split

IMG_SIZE = 64

def load_image(path):
    img = Image.open(path).convert("L")
    img = img.resize((IMG_SIZE, IMG_SIZE))
    return np.array(img).flatten() / 255.0

X = np.stack(df["image_path"].apply(load_image).values)
y = df["head circumference (mm)"].values

X_train, X_val, y_train, y_val = train_test_split(
    X, y, test_size=0.2, random_state=42
)

from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(
    n_estimators=100,
    max_depth=None,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)

from sklearn.metrics import mean_absolute_error

y_pred = rf.predict(X_val)
mae = mean_absolute_error(y_val, y_pred)
mae

results = []

for n in [50, 100, 200]:
    for d in [None, 10, 20]:
        model = RandomForestRegressor(
            n_estimators=n,
            max_depth=d,
            random_state=42,
            n_jobs=-1
        )
        model.fit(X_train, y_train)
        pred = model.predict(X_val)
        mae = mean_absolute_error(y_val, pred)
        results.append((n, d, mae))

results_df = pd.DataFrame(results, columns=["n_estimators", "max_depth", "MAE"])
results_df